;+
; I guess nested modules are the only way to define packages?
;-
module com {

    module zackehh {

        module corba {

            module common {

                struct Reading {
                    long long time;
                    long measurement;
                };

                struct SensorTuple {
                    string zone;
                    string sensor;
                };

                struct SensorMeta {
                    SensorTuple tuple;
                    long alert_level;
                };

                struct Alert {
                    Reading reading;
                    SensorTuple pair;
                };

                typedef sequence<Reading> Readings;
                typedef sequence<string> Zones;
                typedef sequence<Alert> AlertLog;

            };

            module sensor {

                interface Sensor {
                    readonly attribute string id;
                    readonly attribute string zone;

                    common::Reading currentReading();
                    common::Readings getReadingLog();
                };

            };

            module lms {

                interface LMS {
                    readonly attribute string name;
                    readonly attribute common::AlertLog alertLog;

                    void receiveAlert(in common::Alert alert);
                    void removeSensor(in common::SensorTuple tuple);

                    common::SensorMeta registerSensor(in string zone);
                };

            };

            module rmc {

                interface RMC {
                    void cancelAlert(in common::SensorTuple tuple);
                    void receiveAlert(in common::Alert alert);
                    boolean testConnection(in string name);

                    common::AlertLog getAlerts();
                };

            };

        };

    };

};