package corba;


/**
* corba/AlertHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

abstract public class AlertHelper
{
  private static String  _id = "IDL:corba/Alert:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.Alert that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.Alert extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = corba.ReadingHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "reading",
            _tcOf_members0,
            null);
          _tcOf_members0 = corba.SensorPairHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "pair",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (corba.AlertHelper.id (), "Alert", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.Alert read (org.omg.CORBA.portable.InputStream istream)
  {
    corba.Alert value = new corba.Alert ();
    value.reading = corba.ReadingHelper.read (istream);
    value.pair = corba.SensorPairHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.Alert value)
  {
    corba.ReadingHelper.write (ostream, value.reading);
    corba.SensorPairHelper.write (ostream, value.pair);
  }

}
