package corba;

/**
* corba/AlertHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class AlertHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Alert value = null;

  public AlertHolder ()
  {
  }

  public AlertHolder (corba.Alert initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.AlertHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.AlertHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.AlertHelper.type ();
  }

}
