package corba;


/**
* corba/Alert.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class Alert implements org.omg.CORBA.portable.IDLEntity
{
  public corba.Reading reading = null;
  public corba.SensorPair pair = null;

  public Alert ()
  {
  } // ctor

  public Alert (corba.Reading _reading, corba.SensorPair _pair)
  {
    reading = _reading;
    pair = _pair;
  } // ctor

} // class Alert
