package corba;


/**
* corba/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public interface LMSOperations 
{
  String name ();
  corba.Alert[] alertLog ();
  void receiveAlert (corba.Alert alert);
  void removeSensor (corba.SensorPair pair);
  corba.SensorMeta registerSensor (String zone);
} // interface LMSOperations
