package corba;


/**
* corba/ReadingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class ReadingsHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Reading value[] = null;

  public ReadingsHolder ()
  {
  }

  public ReadingsHolder (corba.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.ReadingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.ReadingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.ReadingsHelper.type ();
  }

}
