package corba;


/**
* corba/Reading.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class Reading implements org.omg.CORBA.portable.IDLEntity
{
  public long time = (long)0;
  public int measurement = (int)0;

  public Reading ()
  {
  } // ctor

  public Reading (long _time, int _measurement)
  {
    time = _time;
    measurement = _measurement;
  } // ctor

} // class Reading
