package corba;

/**
* corba/ReadingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class ReadingHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Reading value = null;

  public ReadingHolder ()
  {
  }

  public ReadingHolder (corba.Reading initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.ReadingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.ReadingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.ReadingHelper.type ();
  }

}
