package corba;

/**
* corba/RMCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class RMCHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.RMC value = null;

  public RMCHolder ()
  {
  }

  public RMCHolder (corba.RMC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.RMCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.RMCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.RMCHelper.type ();
  }

}
