package corba;


/**
* corba/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public interface RMCOperations 
{
  void cancelAlert (corba.SensorPair pair);
  void receiveAlert (corba.Alert alert);
  corba.Alert[] getAlerts ();
} // interface RMCOperations
