package corba;


/**
* corba/RMCPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public abstract class RMCPOA extends org.omg.PortableServer.Servant
 implements corba.RMCOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("cancelAlert", new java.lang.Integer (0));
    _methods.put ("receiveAlert", new java.lang.Integer (1));
    _methods.put ("getAlerts", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/RMC/cancelAlert
       {
         corba.SensorPair pair = corba.SensorPairHelper.read (in);
         this.cancelAlert (pair);
         out = $rh.createReply();
         break;
       }

       case 1:  // corba/RMC/receiveAlert
       {
         corba.Alert alert = corba.AlertHelper.read (in);
         this.receiveAlert (alert);
         out = $rh.createReply();
         break;
       }

       case 2:  // corba/RMC/getAlerts
       {
         corba.Alert $result[] = null;
         $result = this.getAlerts ();
         out = $rh.createReply();
         corba.AlertLogHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/RMC:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RMC _this() 
  {
    return RMCHelper.narrow(
    super._this_object());
  }

  public RMC _this(org.omg.CORBA.ORB orb) 
  {
    return RMCHelper.narrow(
    super._this_object(orb));
  }


} // class RMCPOA
