package corba;


/**
* corba/SensorPair.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class SensorPair implements org.omg.CORBA.portable.IDLEntity
{
  public String zone = null;
  public String sensor = null;

  public SensorPair ()
  {
  } // ctor

  public SensorPair (String _zone, String _sensor)
  {
    zone = _zone;
    sensor = _sensor;
  } // ctor

} // class SensorPair
