package corba;

/**
* corba/SensorPairHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class SensorPairHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.SensorPair value = null;

  public SensorPairHolder ()
  {
  }

  public SensorPairHolder (corba.SensorPair initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.SensorPairHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.SensorPairHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.SensorPairHelper.type ();
  }

}
