package corba;


/**
* corba/SensorMetaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

abstract public class SensorMetaHelper
{
  private static String  _id = "IDL:corba/SensorMeta:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.SensorMeta that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.SensorMeta extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = corba.SensorPairHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "pair",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "alert_level",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (corba.SensorMetaHelper.id (), "SensorMeta", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.SensorMeta read (org.omg.CORBA.portable.InputStream istream)
  {
    corba.SensorMeta value = new corba.SensorMeta ();
    value.pair = corba.SensorPairHelper.read (istream);
    value.alert_level = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.SensorMeta value)
  {
    corba.SensorPairHelper.write (ostream, value.pair);
    ostream.write_long (value.alert_level);
  }

}
