package corba;

/**
* corba/SensorMetaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class SensorMetaHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.SensorMeta value = null;

  public SensorMetaHolder ()
  {
  }

  public SensorMetaHolder (corba.SensorMeta initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.SensorMetaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.SensorMetaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.SensorMetaHelper.type ();
  }

}
