package corba;


/**
* corba/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public interface SensorOperations 
{
  String id ();
  String zone ();
  int currentReading ();
  corba.Reading[] getReadingLog ();
} // interface SensorOperations
