package corba;


/**
* corba/SensorMeta.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from flood-warning.idl
* Tuesday, March 24, 2015 1:43:22 PM GMT
*/

public final class SensorMeta implements org.omg.CORBA.portable.IDLEntity
{
  public corba.SensorPair pair = null;
  public int alert_level = (int)0;

  public SensorMeta ()
  {
  } // ctor

  public SensorMeta (corba.SensorPair _pair, int _alert_level)
  {
    pair = _pair;
    alert_level = _alert_level;
  } // ctor

} // class SensorMeta
